export {
  isScriptLoaded,
  loadExternalScript,
  loadScript,
  unloadScript,
} from "./load-script";

// export {
//     canUseWebP,
//     isWindow,
//     isTouch,
//     isBrowser,
//     isIE,
//     hasDocumentSupport,
//     hasIntersectionObserverSupport,
//     hasNavigatorSupport,
//     hasWindowSupport,
//     userAgent,
// } from "./check-browser-specifics"

export {
  isString,
  isArray,
  isBoolean,
  isDate,
  isFunction,
  isNull,
  isNumber,
  isObject,
  isSymbol,
  isUndefined,
  isRegExp,
  isValidColor,
  isValidSize,
  isClient,
  isDefined,
  isEmpty,
  isValidURL,
} from "./check-type";

export {
  scrollToTop,
  o_O,
  arrayDiff,
  camelize,
  convertToUnit,
  kebabCase,
  keyCodes,
  objectMerge,
  randomStr,
  upperFirst,
  slugify,
  cloneObject,
  flatten,
  formatParams,
  makeBlankSrc,
  strBetween,
  addPrefetch,
  copyToClipBoard,
  getQueryParams,
  sortArrayOfObjects,
  generateUUID,
} from "./functions";

export {
  capitalize,
  getBase64,
  getName,
  lowercase,
  naturalSort,
  numberFormat,
  numberRange,
  prettierUrl,
  uppercase,
  ucwords,
  dehyphenate,
  cartesian,
} from "./unsorted";
